import { useEffect, useState } from 'react';
import { useNavigate, useParams, Link } from 'react-router-dom';
import api from '../../api/axios';
import toast from 'react-hot-toast';
const CATS = ['Electronics','Clothing','Home','Sports','Books','Beauty','Toys','Automotive'];
const EMPTY = { name:'', description:'', price:'', originalPrice:'', category:'Electronics', brand:'', image:'', stock:'', rating:'4.5', isFeatured:false, isFlashSale:false, flashSalePrice:'', flashSaleEnds:'', tags:'' };
export default function ProductForm() {
  const { id } = useParams(); const isEdit = Boolean(id); const [form, setForm] = useState(EMPTY); const [loading, setLoading] = useState(false); const [uploading, setUploading] = useState(false); const navigate = useNavigate();
  useEffect(() => { if(isEdit) api.get(`/products/${id}`).then(({data}) => setForm({ name:data.name, description:data.description, price:data.price, originalPrice:data.originalPrice||'', category:data.category, brand:data.brand||'', image:data.image, stock:data.stock, rating:data.rating, isFeatured:data.isFeatured||false, isFlashSale:data.isFlashSale||false, flashSalePrice:data.flashSalePrice||'', flashSaleEnds:data.flashSaleEnds?data.flashSaleEnds.slice(0,16):'', tags:(data.tags||[]).join(', ') })).catch(() => navigate('/admin/products')); }, [id]);
  const set = (k,v) => setForm(f => ({...f,[k]:v}));
  const handleUpload = async (e) => { const file = e.target.files[0]; if(!file) return; setUploading(true); try { const fd = new FormData(); fd.append('image',file); const {data} = await api.post('/products/upload', fd, {headers:{'Content-Type':'multipart/form-data'}}); set('image',data.imageUrl); toast.success('Uploaded!'); } catch { toast.error('Upload failed'); } finally { setUploading(false); } };
  const handleSubmit = async (e) => { e.preventDefault(); if(!form.image) return toast.error('Image required'); setLoading(true);
    try { const payload = {...form, price:Number(form.price), originalPrice:Number(form.originalPrice)||0, stock:Number(form.stock), rating:Number(form.rating), tags:form.tags?form.tags.split(',').map(t=>t.trim()).filter(Boolean):[], flashSalePrice:form.flashSalePrice?Number(form.flashSalePrice):null, flashSaleEnds:form.flashSaleEnds||null };
    if(isEdit) await api.put(`/products/${id}`, payload); else await api.post('/products', payload); toast.success(isEdit?'Updated!':'Created!'); navigate('/admin/products'); }
    catch(err) { toast.error(err.response?.data?.message||'Failed'); } finally { setLoading(false); } };
  return (
    <div className="max-w-3xl"><div className="flex items-center gap-3 mb-6"><Link to="/admin/products" className="link text-sm">← Products</Link><span className="text-az-muted dark:text-dk-muted">/</span><h1 className="text-xl font-bold text-az-text dark:text-dk-text">{isEdit?'Edit':'Add'} Product</h1></div>
    <form onSubmit={handleSubmit} className="space-y-4">
      <div className="bg-white dark:bg-dk-card border border-az-border dark:border-dk-border rounded p-5"><h2 className="font-bold text-az-text dark:text-dk-text text-sm mb-4 pb-3 border-b border-az-border dark:border-dk-border">Basic Info</h2><div className="space-y-4"><div><label className="label">Product Name *</label><input required value={form.name} onChange={e=>set('name',e.target.value)} className="input" /></div><div><label className="label">Description *</label><textarea required rows={4} value={form.description} onChange={e=>set('description',e.target.value)} className="input resize-none"/></div><div className="grid grid-cols-2 gap-4"><div><label className="label">Category *</label><select required value={form.category} onChange={e=>set('category',e.target.value)} className="input">{CATS.map(c=><option key={c}>{c}</option>)}</select></div><div><label className="label">Brand</label><input value={form.brand} onChange={e=>set('brand',e.target.value)} className="input"/></div></div></div></div>
      <div className="bg-white dark:bg-dk-card border border-az-border dark:border-dk-border rounded p-5"><h2 className="font-bold text-az-text dark:text-dk-text text-sm mb-4 pb-3 border-b border-az-border dark:border-dk-border">Pricing & Inventory</h2><div className="grid grid-cols-2 sm:grid-cols-4 gap-4"><div><label className="label">Sale Price *</label><input type="number" required min="0" step="0.01" value={form.price} onChange={e=>set('price',e.target.value)} className="input" placeholder="29.99"/></div><div><label className="label">Original Price</label><input type="number" min="0" step="0.01" value={form.originalPrice} onChange={e=>set('originalPrice',e.target.value)} className="input" placeholder="39.99"/></div><div><label className="label">Stock *</label><input type="number" required min="0" value={form.stock} onChange={e=>set('stock',e.target.value)} className="input"/></div><div><label className="label">Rating</label><input type="number" min="0" max="5" step="0.1" value={form.rating} onChange={e=>set('rating',e.target.value)} className="input"/></div></div></div>
      <div className="bg-white dark:bg-dk-card border border-az-border dark:border-dk-border rounded p-5"><h2 className="font-bold text-az-text dark:text-dk-text text-sm mb-4 pb-3 border-b border-az-border dark:border-dk-border">Flash Sale</h2><label className="flex items-center gap-3 cursor-pointer mb-4"><input type="checkbox" checked={form.isFlashSale} onChange={e=>set('isFlashSale',e.target.checked)} className="w-4 h-4 accent-orange-500"/><span className="text-sm font-medium text-az-text dark:text-dk-text">Enable Flash Sale</span></label>{form.isFlashSale&&<div className="grid grid-cols-2 gap-4"><div><label className="label">Flash Price</label><input type="number" min="0" step="0.01" value={form.flashSalePrice} onChange={e=>set('flashSalePrice',e.target.value)} className="input" placeholder="19.99"/></div><div><label className="label">Sale Ends</label><input type="datetime-local" value={form.flashSaleEnds} onChange={e=>set('flashSaleEnds',e.target.value)} className="input"/></div></div>}</div>
      <div className="bg-white dark:bg-dk-card border border-az-border dark:border-dk-border rounded p-5"><h2 className="font-bold text-az-text dark:text-dk-text text-sm mb-4 pb-3 border-b border-az-border dark:border-dk-border">Image</h2><div className="grid sm:grid-cols-2 gap-4"><div><label className="label">Upload File</label><input type="file" accept="image/*" onChange={handleUpload} id="img-up" className="hidden"/><label htmlFor="img-up" className={`flex items-center justify-center w-full border-2 border-dashed border-az-border dark:border-dk-border rounded px-4 py-8 cursor-pointer hover:border-az-orange transition-colors ${uploading?'opacity-50':''}`}><div className="text-center"><p className="text-az-muted dark:text-dk-muted text-sm">{uploading?'Uploading...':'Click to upload'}</p><p className="text-xs text-az-muted dark:text-dk-muted mt-1">Max 5MB</p></div></label></div><div><label className="label">Or Image URL</label><input value={form.image} onChange={e=>set('image',e.target.value)} className="input mb-2" placeholder="https://..."/>{form.image&&<div className="h-28 bg-az-bg dark:bg-dk-nav border border-az-border dark:border-dk-border rounded overflow-hidden"><img src={form.image} alt="" className="w-full h-full object-contain p-2" onError={e=>e.target.style.display='none'}/></div>}</div></div></div>
      <div className="bg-white dark:bg-dk-card border border-az-border dark:border-dk-border rounded p-5"><h2 className="font-bold text-az-text dark:text-dk-text text-sm mb-4 pb-3 border-b border-az-border dark:border-dk-border">Additional</h2><div className="space-y-4"><div><label className="label">Tags (comma-separated)</label><input value={form.tags} onChange={e=>set('tags',e.target.value)} className="input" placeholder="wireless, bluetooth"/></div><label className="flex items-center gap-3 cursor-pointer"><input type="checkbox" checked={form.isFeatured} onChange={e=>set('isFeatured',e.target.checked)} className="w-4 h-4 accent-orange-500"/><div><span className="text-sm font-medium text-az-text dark:text-dk-text">Featured on Homepage</span></div></label></div></div>
      <div className="flex gap-3"><button type="submit" disabled={loading||uploading} className="btn-primary px-8">{loading?'Saving...':isEdit?'Update':'Create'}</button><Link to="/admin/products" className="btn-secondary px-6">Cancel</Link></div>
    </form></div>
  );
}
